name: BuildImage
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: GetCode
        uses: actions/checkout@v4
        with:
          repository: BtbN/FFmpeg-Builds
      - name: Build
        shell: bash
        run: |
          sudo apt-get clean
          docker system prune -a -f
          ./makeimage.sh win64 gpl-shared 7.0
          docker ps -a
      - name: UploadBin
        uses: actions/upload-artifact@v4
        with:
          path: artifacts
