name: CPython
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: python/cpython
          ref: ${{ github.event.inputs.version }}
      - name: Build
        shell: pwsh
        run: |
          PCbuild/build.bat -e --pgo
          python PC/layout --copy=dist --preset-embed
      - name: Result
        uses: actions/upload-artifact@v7
        with:
          path: dist/*
          name: ${{ github.event.inputs.version }}
          include-hidden-files: true
