name: BuildPython
on: workflow_dispatch
jobs:
  Build:
    runs-on: windows-2019
    steps:
      - name: GetCode
        uses: actions/checkout@v4
        with:
          repository: python/cpython
          ref: refs/tags/v3.10.15
      - name: Build
        shell: pwsh
        run: |
          PCbuild/get_externals.bat
          PCbuild/build.bat -e --pgo -p x64 -t build
          Tools/msi/buildrelease.bat -x64 --skip-doc --skip-msi
      - name: UploadBin
        uses: actions/upload-artifact@v4
        with:
          path: PCbuild/amd64/*
