name: Build Python
on: push
jobs:
  build:
    runs-on: windows-21H2
    steps:
      - name: Get source code
        uses: microsoft/setup-msbuild@v2
          with:
            vs-version: 2017
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri 'https://www.python.org/ftp/python/3.10.14/Python-3.10.14.tar.xz' -OutFile Python-3.10.14.tar.xz
          tar -xf Python-3.10.14.tar.xz
          cd Python-3.10.14/PCbuild/
          ./get_externals.bat
          cd ../Tools/msi/
          ./get_externals.bat
          ./buildrelease.bat -o ../../PCbuild/
        - name: upload-artifact
          uses: actions/upload-artifact@v4
          with:
            name: result
            path: ../../PCbuild/*

