name: Build Python
on: push
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          repository: python/cpython
          ref: refs/tags/v3.10.14
      - name: build
        shell: pwsh
        run: |
          cd PCbuild/
          ./get_externals.bat
          cd ../Tools/msi/
          ./get_externals.bat
          ./buildrelease.bat -x64 --skip-doc --skip-msi
          cd ../../
          tree /F > a.txt
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          path: a.txt
