name: PortableQemu
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Extract
        shell: pwsh
        run: |
          curl -L -o qemu.exe 'https://qemu.weilnetz.de/w64/qemu-w64-setup-20250210.exe'
          mkdir qemu
          ./qemu.exe /S /D=qemu
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: qemu/*
