name: PortableQemu
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Extract
        shell: pwsh
        run: |
          curl 'https://qemu.weilnetz.de/w64/qemu-w64-setup-20250210.exe' -L -O
          ./qemu-w64-setup-20250210.exe /S /D=./qemu
          tree /F
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: qemu
