name: Temp
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: saivert/pwvucontrol
          ref: 0.5.3
          fetch-depth: 1
      - name: Build
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y meson libgtk-4-dev libglib2.0-dev libgtk-4-dev libadwaita-1-dev libpipewire-0.3-dev libwireplumber-0.5-dev pkg-config gettext desktop-file-utils libglib2.0-bin libxml2-utils
          meson setup builddir
          meson compile -C builddir
          meson install -C builddir
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Result
          path: builddir
          include-hidden-files: true
