name: Temp
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: saivert/pwvucontrol
          ref: 0.5.3
          fetch-depth: 1
      - name: Build
        shell: bash
        run: |
          apt update
          apt install meson
          meson setup builddir
          meson compile -C builddir
          meson install -C builddir
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Result
          path: builddir
          include-hidden-files: true
