name: Temp
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: yorukot/superfile
          ref: v1.6.0
          fetch-depth: 1
      - name: Build
        shell: bash
        run: |
          sed -i '164d' src/internal/common/string_function.go
          sed -i '161s/Bin/Dec/' src/internal/common/string_function.go
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -trimpath -gcflags="-l=4" -o spf.exe
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Result
          path: spf.exe
          include-hidden-files: true
